#!/bin/bash

# THIS SCRIPT ITERATES OVER NAMESPACES IN CURRENT KUBERNETES CLUSTER AND LISTS ALL PODS. CHECKS FOR PRESENCE OF /etc/lsb-release FILE (CUSTOM BUILD IMAGES)
# AND LOOKS UP DISTRIBUTION AND VERSION OF BASE IMAGE. IMAGE NAMES WITH POD NAMES AND THEIR NAMESPACES ARE WRITTEN TO CONSOLE AND SAVED TO FILE

IFS=$'\n'

# CHECK IF KUBECTL IS INSTALLED
kubectl version > /dev/null
if [[ $? -ne 0 ]] ; then
	echo "kubectl is not installed! Aborting..."
	exit 1
fi

# OUTPUT FILES
OUTPUT_FOUND="images-found.txt"
OUTPUT_NOT_FOUND="images-not-found.txt"
OUTPUT_TO_CHECK="TO_CHECK.txt"

# OUTPUT ARRAYS
FOUND=("FOLLOWING PODS HAS ONLY ONE IMAGE WITH RECOGNIZED OS VERSION:")
NOT_FOUND=("FOLLOWING PODS DOES NOT CONTAINT /etc/lsv-release FILE - CAN'T REGOGNIZE BASE IMAGE OS")
TO_CHECK=("FOLLOWING PODS SHOULD BE CHECKED MANUALLY (MORE THAN ONE CONTAINER)")

# ITERATE OVER NAMESPACES
for NAMESPACE in $(kubectl get namespaces | awk '{print $1}') ; do
	
	#skip first line
	if [[ $c1 -eq 0 ]] ; then ((c1++)) ; continue ; fi

	# print namespace header
	echo -e "\e[33m\nNAMESPACE: $NAMESPACE\e[0m"
	
	# ITERATE OVER PODS IN NAMESPACE
	for POD in $(kubectl get pods -n $NAMESPACE | awk '{print $1}') ; do
		# skip first line
		if [[ $c2 -eq 0 ]] ; then ((c2++)) ; continue ; fi

		# GET OS INFO
		OS_INFO=$(kubectl exec $POD -n $NAMESPACE -- cat /etc/lsb-release 2> /dev/null )	
		
		# PARSE OS DETAILS MESSAGE	
		if [[ $OS_INFO =~ "DISTRIB_DESCRIPTION=" ]] ; then
			OS_INFO="${OS_INFO##*$'\n'}"
			
			# get image from current pod
			IMAGE=$(kubectl describe pod $POD -n $NAMESPACE | grep "Image:" | awk '{print $2}')
			if [[ $(echo $IMAGE | wc -w) -gt 1 ]] ; then 
				echo -e "\e[31mMULTIPLE CONTAINERS FOUND IN POD: $POD (NAMESPACE: $NAMESPACE) - MANUAL VERIFICATION NEEDED\e[0m"
			        TO_CHECK+=("$POD (namespace: $NAMESPACE)")
				continue;
			fi
			echo -e "\e[32m$POD - $(echo "$OS_INFO " | cut -c 21-)- $IMAGE \e[0m"
			FOUND+=("$IMAGE = $OS_INFO")
		else 
			echo -ne "$POD - "
			echo "NO OS INFO FOUND"
			NOT_FOUND+=("$POD (namespace: $NAMESPACE)")
		fi
	done
	c2=0	#reset line skipping counter2
done

# CLEAR OUTPUT FILES
echo -n "" > $OUTPUT_FOUND
echo -n "" > $OUTPUT_NOT_FOUND
echo -n "" > $OUTPUT_TO_CHECK

# SAVE RESULTS TO FILE
for line in "${FOUND[@]}" ; do
	echo $line >> $OUTPUT_FOUND;
done

for line in "${NOT_FOUND[@]}" ; do
        echo $line >> $OUTPUT_NOT_FOUND;
done

for line in "${TO_CHECK[@]}" ; do
        echo $line >> $OUTPUT_TO_CHECK;
done

echo "removing duplicates..."

# REMOVE DUPLICATES
#TMP=$(cat $OUTPUT_FOUND | uniq)
#echo $TMP > $OUTPUT_FOUND

#TMP=$(cat $OUTPUT_NOT_FOUND | uniq)
#echo $TMP > $OUTPUT_NOT_FOUND

#TMP=$(cat $OUTPUT_TO_CHECK | uniq)
#echo $TMP > $OUTPUT_TO_CHECK


echo "done."
